- name: data types
  hosts: localhost
  vars:
    place: hyderabad
    location:
      - tankbund
      - zoopark
      - birla mandir
    costs:
      movie: 300
      lunch: 500

  tasks:
    - name: TASK1
      ansible.builtin.debug:
        msg: "after visiting {{place}}, must visit places {{location}} and after that {{costs}}"
