- name: installing the nginx
  hosts: localhost
  tasks:  
        - name: started installation
          ansible.builtin.dnf:
            name: nginx
            state:  present
        - name: enabiling the nginx
          ansible.builtin.service:
            name: nginx
            state: started
            enabled: yes
  
    
      