- name: variables declaration
  hosts: localhost
  vars:
    greetings: "hello"
    last_name:  "kaparthi"
  tasks:
    - name: variables used in tasks
      ansible.builtin.debug:
        msg: "{{greetings}}, sricharan,{{last_name}}."
