- name: variables in ansible
  hosts: localhost
  vars:
    firstname: "sricharan"
    lastname: "kaparthi"

  tasks:
    ansible.builtin.debug:
      msg: "my first name {{firstname}},last name {{lastname}}."
