- name: variables declaration
  hosts:  localhost
  var:
    first_name: "sricharan"
    last_name:  "kaparthi"
  tasks:
    - name: variables used in tasks
      ansible.builtin.debug:
        msg:  "{{ first_name }}, Let’s learn Ansible variables"